### PR TITLE
Add more invoice templates to builder

### LINKED ISSUE #59: Visual Editor: examples
* When using the editor for the first time on an empty document, it can be frustrating to have to tap "+" for each individual field.

One possible solution would be to define "empty examples" for a specific set of schemas. When adding an `org.Party` for example, something like the following JSON would be used:

```json
{
  "name": "",
  "tax_id": {
     "country": "",
     "code": ""
  },
  "addresses": [
     {
       "num": "",
       "street": "",
       "locality": "",
       "region": ""
     }
  ],
  "emails": [
     {
        "addr": ""
     }
  ]
}
```

While not so useful for JSON, this would produce a lot of empty boxes in the Visual editor which can be easily removed later.

### PR DESCRIPTION
**Pull request by beliolfa**
Closes #59

### CODE REVIEW

**Comment by beliolfa** [comment]
@samlown used an accordion instead of a select

**Comment by samlown** [comment]
@beliolfa nice! I like the accordion! My only suggestion would be to keep it closed when opening the modal, we don't want to suggest any tax regime is more important than another.

**Review by samlown — APPROVED** [review]
Nice! I'd just remove the "default to 'CO'" thing before launch.

**Comment by beliolfa** [comment]
@samlown fixed and merged!

**Pull request merged**
